// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: SequentialCommandGroup.

package robot.commands;
import edu.wpi.first.wpilibj2.command.SequentialCommandGroup;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import robot.subsystems.drivetrainSubSys;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/*
 *
 */
public class autoDriveCmdGrp1 extends SequentialCommandGroup {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    public autoDriveCmdGrp1(drivetrainSubSys drivetrainSubSys){

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    
    
    addCommands(
        // Add Commands here:
        // Also add parallel commands using the
        //
        // addCommands(
        //      new command1(argsN, subsystem),
        //      parallel(
        //          new command2(argsN, subsystem),
        //          new command3(argsN, subsystem)
        //      )    
        //  );

        //---------------  Positive hdg for right, Negative for left-----------------\\

        //  Forward   (  dist,   pwr,    hdg,         Mode,        timeOut,   BrakeFlag,  subsystem)

        //    Turn    (rightPwr, leftPwr,   hdg,   dist,  mode,   to,         brakeFlag,  subsystem)
        
        new driveFwdCmd(95.0,   0.20,    20.0,    "CURRENT_HEADING",   15.0,      false,   drivetrainSubSys)

        //new driveTurnCmd(0.5,     -0.5,    -180.0,  0.0,  "N/A", 15.0,          false,   drivetrainSubSys),

        //new driveFwdCmd(60.0,   0.5,    0.0,    "CURRENT_HEADING",   15.0,      false,   drivetrainSubSys)


















        );
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}
